import '@/styles/globals.css'
import Nav from '@/components/ui/nav'
import Footer from '@/components/ui/footer'
import Provider from '@/components/provider'
import { Alert } from '@/components/Alert'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Provider>
      <div className="flex flex-col min-h-screen">
        <Nav/>
        <main className="flex-1 bg-white">
          <Alert/>
          {children}
        </main>
        <Footer/>
        </div>
      </Provider>
        </body>
    </html>
  )
}
